import { StyleSheet } from "react-native";

const themeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#121212',
    paddingHorizontal: 15,
  },
  movieListHeader: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#ff8c00',
    paddingVertical: 15,
    textAlign: 'center',
    letterSpacing: 1.2,
  },
  movieListCard: {
    flexDirection: 'row',
    backgroundColor: '#1e1e1e',
    borderRadius: 12,
    marginVertical: 10,
    elevation: 4,
    shadowColor: '#000',
    shadowOpacity: 0.7,
    shadowRadius: 6,
    shadowOffset: { width: 2, height: 4 },
  },
  movieListPoster: {
    width: 90,
    height: 140,
    borderTopLeftRadius: 12,
    borderBottomLeftRadius: 12,
    backgroundColor: '#333',
  },
  movieListCardContent: {
    flex: 1,
    padding: 15,
    justifyContent: 'center',
  },
  movieListTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
  },
  movieListSubtitle: {
    fontSize: 14,
    color: '#ccc',
    marginTop: 4,
  },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#121212',
  },
  movieDetailsContainer: {
    flex: 1,
    backgroundColor: '#121212',
    padding: 15,
  },
  movieDetailsTitle: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#ff8c00',
    marginVertical: 10,
  },

  movieDetailsPoster: {
    width: '100%',
    height: 300,
    borderRadius: 12,
  },
  movieDetailsFavoriteContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',  
    alignItems: 'center',
    marginVertical: 10,
    width: '100%',                    
    paddingHorizontal: 5,             
  },
  movieDetailsRating: {
    color: '#fff',
    fontSize: 16,
  }, 
  movieDetailsRatingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  movieDetailsRatingText: {
    color: '#fff',
    fontSize: 16,
  }, 
  movieDetailsDescription: {
    color: '#ccc',
    fontSize: 16,
    marginVertical: 10,
  },
  movieDetailsCastHeader: {
    color: '#ff8c00',
    fontSize: 20,
    fontWeight: 'bold',
    marginVertical: 10,
  },
  movieDetailsCastList: {
    paddingVertical: 10,
  },
  movieDetailsCastMember: {
    width: 100,
    marginRight: 15,
    alignItems: 'center',
  },
  movieDetailsCastImage: {
    width: 80,
    height: 120,
    borderRadius: 8,
    backgroundColor: '#333',
  },
  movieDetailsCastName: {
    color: '#fff',
    marginTop: 8,
    textAlign: 'center',
  },
  movieDetailsGenresContainer: {
    marginVertical: 10
  },
  movieDetailsGenreBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#2a2a2a',
    borderRadius: 15,
    marginRight: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  movieDetailsGenreText: {
    color: '#ff8c00',
    fontWeight: '600',
    fontSize: 14,
  },
  movieDetailsHeartOverlay: {
    position: 'absolute',
    top: '35%',
    left: '38%',
    zIndex: 10,
  },
  movieDetailsPosterContainer: {
    position: 'relative',
    alignItems: 'center',
  },
  movieDetailsDescriptionContainer: {
    maxHeight: 110, 
    marginVertical: 10,
    scrollEnabled: false,
  },
  searchMoviesButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginVertical: 10,
  },
  searchMoviesBtn: {
    paddingVertical: 10,
    paddingHorizontal: 60,
    borderRadius: 25,
    borderWidth: 1,
    borderColor: '#ff8c00',
    backgroundColor: 'transparent',
  },
  searchMoviesBtnActive: {
    backgroundColor: '#ff8c00',
  },
  searchMoviesBtnText: {
    color: '#ff8c00',
    fontWeight: '600',
    fontSize: 16,
  },
  searchMoviesBtnTextActive: {
    color: '#121212',
  },
  searchMoviesSearchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 10,
    position: 'relative',
  },
  searchMoviesSearchIcon: {
    position: 'absolute',
    left: 15,
    zIndex: 10,
  },
  searchMoviesTextInputWithIcon: {
    flex: 1,
    height: 40,
    backgroundColor: '#1e1e1e',
    borderRadius: 20,
    paddingLeft: 40,
    color: '#fff',
    fontSize: 16,
  },
  searchMoviesClearIconContainer: {
    position: 'absolute',
    right: 15,
    zIndex: 15,
  },
  searchMoviesSearchBtn: {
    marginLeft: 10,
    backgroundColor: '#ff8c00',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
  },
  searchMoviesSearchBtnText: {
    color: '#121212',
    fontWeight: 'bold',
  },
  searchMoviesFilterButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 10,
    
  },
  searchMoviesFilterBtn: {
    paddingVertical: 8,
    paddingHorizontal: 45,
    borderRadius: 20,
    borderColor: '#ff8c00',
    borderWidth: 1,
    marginHorizontal: 10,
  },
  searchMoviesFilterBtnActive: {
    backgroundColor: '#ff8c00',
  },
  searchMoviesFilterBtnText: {
    color: '#ff8c00',
    fontWeight: '600',
    fontSize: 15,
  },
  searchMoviesFilterBtnTextActive: {
    color: '#121212',
  },
  searchMoviesDropdownWrapper: {
    marginHorizontal: 10,
    marginBottom: 10,
    height: 40,
  },
  searchMoviesDropdown: {
    height: 50,
    borderColor: '#ff8c00',
    borderWidth: 1,
    borderRadius: 20,
    paddingHorizontal: 15,
    backgroundColor: '#1e1e1e',
  },
  searchMoviesPlaceholderStyle: {
    color: '#888',
    fontSize: 16,
  },
  searchMoviesSelectedTextStyle: {
    color: '#fff',
    fontSize: 16,
  },
  searchMoviesIconStyle: {
    tintColor: '#ff8c00',
    width: 20,
    height: 20,
  },
  searchMoviesDropdownContainerStyle: {
    backgroundColor: '#1e1e1e',
    borderRadius: 10,
  },
  searchMoviesGridCard: {
    flex: 1,
    margin: 8,
    maxWidth: '45%',
    alignItems: 'center',
  },
  searchMoviesGridPoster: {
    width: '100%',
    aspectRatio: 2 / 3,
    borderRadius: 12,
    backgroundColor: '#333',
  },
  searchMoviesGridTitle: {
    marginTop: 8,
    color: '#fff',
    fontWeight: '600',
    fontSize: 14,
    textAlign: 'center',
  },
  searchMoviesCenter: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchMoviesDropdownItem: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#2c2c2c', 
  },
  searchMoviesDropdownItemSelected: {
    backgroundColor: '#ff8c00',
    borderRadius: 8,
  },
  searchMoviesDropdownItemText: {
    color: '#fff', 
    fontSize: 16,
  },
  searchMoviesDropdownItemTextSelected: {
    color: '#121212', 
    fontWeight: '700',
    fontSize: 16,
  },
  registerContainer: {
    flex: 1,
    backgroundColor: '#121212',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  registerContent: {
    backgroundColor: '#1e1e1e',
    borderRadius: 12,
    padding: 20,
  },
  registerTitle: {
    fontSize: 28,
    color: '#ff8c00',
    fontWeight: 'bold',
    marginBottom: 24,
    textAlign: 'center',
  },
  registerInput: {
    backgroundColor: '#333',
    color: '#fff',
    borderRadius: 8,
    paddingHorizontal: 15,
    paddingVertical: 12,
    fontSize: 16,
    marginBottom: 16,
  },
  registerButton: {
    backgroundColor: '#ff8c00',
    borderRadius: 30,
    paddingVertical: 14,
    marginTop: 10,
    alignItems: 'center',
  },
  registerButtonText: {
    color: '#121212',
    fontSize: 18,
    fontWeight: '700',
  },
  registerErrorText: {
    color: '#ff4d4d',
    marginBottom: 12,
    textAlign: 'center',
  },
  registerLoginContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 15,
  },
  registerLoginText: {
    color: '#ccc',
    fontSize: 14,
  },
  registerLoginButtonText: {
    color: '#ff8c00',
    fontSize: 14,
    fontWeight: '600',
  },
  loginContainer: {
    flex: 1,
    backgroundColor: '#121212',
    justifyContent: 'flex-start',
    paddingHorizontal: 20,
  },
  loginContent: {
    backgroundColor: '#1e1e1e',
    borderRadius: 12,
    padding: 20,
  },
  loginTitle: {
    fontSize: 28,
    color: '#ff8c00',
    fontWeight: 'bold',
    marginBottom: 24,
    textAlign: 'center',
  },
  loginInput: {
    backgroundColor: '#333',
    color: '#fff',
    borderRadius: 8,
    paddingHorizontal: 15,
    paddingVertical: 12,
    fontSize: 16,
    marginBottom: 16,
  },
  loginButton: {
    backgroundColor: '#ff8c00',
    borderRadius: 30,
    paddingVertical: 14,
    marginTop: 10,
    alignItems: 'center',
  },
  loginButtonText: {
    color: '#121212',
    fontSize: 18,
    fontWeight: '700',
  },
  loginErrorText: {
    color: '#ff4d4d',
    marginBottom: 12,
    textAlign: 'center',
  },
  loginRegisterContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 15,
  },
  loginRegisterText: {
    color: '#ccc',
    fontSize: 14,
  },
  loginRegisterButtonText: {
    color: '#ff8c00',
    fontSize: 14,
    fontWeight: '600',
  },
  profilContainer: {
    flex: 1,
    backgroundColor: '#121212',
    paddingHorizontal: 20,
  },
  profilHeader: {
    paddingVertical: 20,
    alignItems: 'center',
  },
  profilHeaderTitle: {
    color: '#fff',
    fontSize: 24,
    fontWeight: 'bold',
  },
  profilTopButtonContainer: {
    paddingTop: 10,
  },
  profilBottomButtonContainer: {
    paddingBottom: 20,
    justifyContent: 'flex-end',
  },
  profilFlexSpacer: {
    flex: 1,
  },
  profilLogoutButton: {
    flexDirection: 'row',
    backgroundColor: '#ff8c00',
    borderRadius: 30,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profilLogoutButtonText: {
    color: '#121212',
    fontSize: 18,
    fontWeight: '700',
  },
  profilDeleteButton: {
    flexDirection: 'row',
    backgroundColor: '#ff4d4d',
    borderRadius: 30,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profilDeleteButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '700',
  },
  profilIcon: {
    marginRight: 10,
  },
  favoriteContainer: {
    flex: 1,
    backgroundColor: '#121212',
  },
  favoriteCenterContainer: {
    flex: 1,
    backgroundColor: '#121212',
    justifyContent: 'center',
    alignItems: 'center',
  },
  favoriteEmptyText: {
    color: '#888',
    fontSize: 18,
  },
  favoriteCard: {
    flex: 1,
    margin: 10,
    maxWidth: '45%',
    backgroundColor: '#1e1e1e',
    borderRadius: 12,
    overflow: 'hidden',
  },
  favoritePoster: {
    width: '100%',
    aspectRatio: 2 / 3,
  },
  favoriteTitle: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 16,
    padding: 8,
  },
  favoriteOverlay: {
    position: 'absolute',
    top: 8,
    right: 8,
  },
  favoriteHeartBtn: {
    padding: 4,
  },
  favoriteFilterContainer: {
    marginHorizontal: 10,
    marginBottom: 10,
  },
  profilInputContainer: {
    marginBottom: 20,
  },
  profilInput: {
    height: 50,
    borderColor: "#888",
    borderWidth: 1,
    borderRadius: 5,
    paddingHorizontal: 10,
    color: "#fff",
    marginBottom: 10,
  },
  favoriteContainer: {
    flex: 1,
    backgroundColor: '#121212',
  },
  favoriteCenterContainer: {
    flex: 1,
    backgroundColor: '#121212',
    justifyContent: 'center',
    alignItems: 'center',
  },
  favoriteEmptyText: {
    color: '#888',
    fontSize: 18,
  },
  favoriteFilterContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 10,
    backgroundColor: '#1e1e1e',
  },
  filterButton: {
    backgroundColor: '#333',
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderRadius: 25,
    alignItems: 'center',
  },
  filterButtonText: {
    color: '#ff8c00',
    fontWeight: '600',
    fontSize: 16,
  },
  searchInput: {
    backgroundColor: '#333',
    color: '#fff',
    borderRadius: 8,
    paddingHorizontal: 15,
    paddingVertical: 10,
    fontSize: 16,
    marginHorizontal: 15,
    marginBottom: 10,
  },
  filterOptionsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingHorizontal: 10,
    marginBottom: 10,
  },
  searchMoviesDropdown: {
    flex: 1,
    height: 40,
    borderColor: '#ff8c00',
    borderWidth: 1,
    borderRadius: 20,
    paddingHorizontal: 15,
    backgroundColor: '#1e1e1e',
    marginHorizontal: 5,
  },
  searchMoviesPlaceholderStyle: {
    color: '#888',
    fontSize: 16,
  },
  searchMoviesSelectedTextStyle: {
    color: '#fff',
    fontSize: 16,
  },
  searchMoviesIconStyle: {
    tintColor: '#ff8c00',
    width: 20,
    height: 20,
  },
  searchMoviesDropdownContainerStyle: {
    backgroundColor: '#1e1e1e',
    borderRadius: 10,
  },
  favoriteCard: {
    flex: 1,
    margin: 10,
    maxWidth: '45%',
    backgroundColor: '#1e1e1e',
    borderRadius: 12,
    overflow: 'hidden',
  },
  favoritePoster: {
    width: '100%',
    aspectRatio: 2 / 3,
  },
  favoriteOverlay: {
    position: 'absolute',
    top: 8,
    right: 8,
  },
  favoriteHeartBtn: {
    padding: 4,
  },
  favoriteTitle: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 16,
    padding: 8,
  },
});

export default themeStyles;